# -*- coding: utf-8 -*-
"""AI Engineering - Practical Fine-Tuning Lab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i64sUB5vKbXt_BkLUZEu90Sb73KxSuC6
"""

!pip install -q transformers datasets peft trl accelerate

!pip install --upgrade -q torchao

import json
from datasets import Dataset

data = [
    {"instruction": "What is FastAPI?", "response": "FastAPI is a modern, high-performance web framework for building APIs with Python 3.8+ based on standard Python type hints and Pydantic."},
    {"instruction": "How do you define a GET endpoint in FastAPI?", "response": "Use the decorator @app.get('/endpoint') on top of an async or synchronous python function."},
    {"instruction": "What is Pydantic in the context of FastAPI?", "response": "Pydantic is a data validation library used by FastAPI to enforce data types, parse request payloads, and generate OpenAPI documentation automatically."},
    {"instruction": "How do you run a FastAPI application locally?", "response": "You run a FastAPI application using an ASGI server like Uvicorn using the command: uvicorn main:app --reload."},
    {"instruction": "What are Path Parameters in FastAPI?", "response": "Path parameters are variable parts of a URL path used to capture values, declared like @app.get('/items/{item_id}')."},
    {"instruction": "How do Query Parameters work in FastAPI?", "response": "Query parameters are key-value pairs added after the '?' in a URL. In FastAPI, function arguments not in the path route automatically become query parameters."},
    {"instruction": "What is the purpose of Depends in FastAPI?", "response": "Depends is used for Dependency Injection in FastAPI, allowing you to share logic, database sessions, and authentication across endpoints cleanly."},
    {"instruction": "How do you define a POST request body in FastAPI?", "response": "Create a class inheriting from Pydantic's BaseModel and pass it as a parameter type hint to your endpoint function."},
    {"instruction": "How do you return custom HTTP status codes in FastAPI?", "response": "Pass the status_code parameter to the route decorator, e.g., @app.post('/items', status_code=201) or import status from fastapi."},
    {"instruction": "What automatically generated documentation does FastAPI offer?", "response": "FastAPI automatically generates interactive Swagger UI docs at '/docs' and ReDoc documentation at '/redoc'."},
    {"instruction": "How do you set up CORS in FastAPI?", "response": "Import CORSMiddleware from fastapi.middleware.cors and add it to the application using app.add_middleware()."},
    {"instruction": "How do you handle background tasks in FastAPI?", "response": "Use the BackgroundTasks parameter in your route function and add callables with background_tasks.add_task()."},
    {"instruction": "How do you raise HTTP errors intentionally in FastAPI?", "response": "Import and raise HTTPException from fastapi with a status_code and detail message."},
    {"instruction": "What is an ASGI server?", "response": "ASGI (Asynchronous Server Gateway Interface) is a standard interface between async Python web servers and web applications."},
    {"instruction": "How do you implement OAuth2 password bearer authentication in FastAPI?", "response": "Use OAuth2PasswordBearer and OAuth2PasswordRequestForm provided by fastapi.security alongside JWT tokens."},
    {"instruction": "How do optional query parameters look in Python type annotations for FastAPI?", "response": "Use Optional[str] = None or str | None = None using typing module."},
    {"instruction": "What is a Response Model in FastAPI?", "response": "The response_model argument in route decorators filters, validates, and formats the data returned by an endpoint."},
    {"instruction": "How do you upload files in FastAPI?", "response": "Use UploadFile and File from fastapi as parameter type hints in your endpoint function."},
    {"instruction": "What is APIRouter used for in FastAPI?", "response": "APIRouter allows you to structure and group endpoints into separate files and modular components for larger applications."},
    {"instruction": "How do synchronous and asynchronous routes differ in FastAPI?", "response": "Async routes ('async def') allow non-blocking execution during I/O operations, whereas standard routes ('def') run in a background thread pool."},
    {"instruction": "What is middleware in FastAPI?", "response": "Middleware is a function that runs before every request is processed and after every response is generated."},
    {"instruction": "How do you test FastAPI endpoints programmatically?", "response": "Use TestClient from fastapi.testclient or httpx to send requests directly to the application in test suites."},
    {"instruction": "How do you define header parameters in FastAPI?", "response": "Import Header from fastapi and set it as default value in parameter definitions, e.g., user_agent: str = Header(None)."},
    {"instruction": "How do you define cookie parameters in FastAPI?", "response": "Import Cookie from fastapi and use it as a parameter default value, e.g., session_id: str | None = Cookie(None)."},
    {"instruction": "How do you stream responses in FastAPI?", "response": "Use StreamingResponse from fastapi.responses and pass an async generator function."},
    {"instruction": "What is Starlette?", "response": "Starlette is a lightweight ASGI framework/toolkit that powers FastAPI's underlying routing and web mechanics."},
    {"instruction": "How do you handle database sessions cleanly in FastAPI routes?", "response": "Create a generator yielding database sessions with yield and inject it via Depends()."},
    {"instruction": "How do you set response headers manually in FastAPI?", "response": "Pass a Response parameter to your endpoint function and modify its response.headers dictionary."},
    {"instruction": "What is a Form parameter in FastAPI?", "response": "Form parameters allow receiving HTML form submission fields instead of JSON payloads via Form(...) from fastapi."},
    {"instruction": "How do you customize root application metadata in FastAPI?", "response": "Pass title, description, and version arguments to the main FastAPI() initialization call."}
]

# Save dataset locally
with open("fastapi_dataset.json", "w") as f:
    json.dump(data, f, indent=2)

# Format for ChatML prompt template
def format_prompt(sample):
    text = f"<|im_start|>user\n{sample['instruction']}<|im_end|>\n<|im_start|>assistant\n{sample['response']}<|im_end|>"
    return {"text": text}

dataset = Dataset.from_dict({"instruction": [d["instruction"] for d in data], "response": [d["response"] for d in data]})
formatted_dataset = dataset.map(format_prompt)

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

model_id = "HuggingFaceTB/SmolLM2-135M-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="auto"
)

# Test 5 baseline questions
test_questions = [
    "What is FastAPI?",
    "What is Pydantic in the context of FastAPI?",
    "What is the purpose of Depends in FastAPI?",
    "How do you run a FastAPI application locally?",
    "What automatically generated documentation does FastAPI offer?"
]

print("=== BEFORE FINE-TUNING RESPONSES ===")
before_responses = []
pipe = pipeline("text-generation", model=model, tokenizer=tokenizer)

for q in test_questions:
    prompt = f"<|im_start|>user\n{q}<|im_end|>\n<|im_start|>assistant\n"
    out = pipe(prompt, max_new_tokens=60, do_sample=False)[0]['generated_text']
    response = out.split("<|im_start|>assistant\n")[-1].replace("<|im_end|>", "").strip()
    before_responses.append(response)
    print(f"\nQ: {q}\nA: {response}")

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

model_id = "HuggingFaceTB/SmolLM2-135M-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map="auto"
)

# Test 5 baseline questions
test_questions = [
    "What is FastAPI?",
    "What is Pydantic in the context of FastAPI?",
    "What is the purpose of Depends in FastAPI?",
    "How do you run a FastAPI application locally?",
    "What automatically generated documentation does FastAPI offer?"
]

print("=== BEFORE FINE-TUNING RESPONSES ===")
before_responses = []
pipe = pipeline("text-generation", model=model, tokenizer=tokenizer)

for q in test_questions:
    prompt = f"<|im_start|>user\n{q}<|im_end|>\n<|im_start|>assistant\n"
    out = pipe(prompt, max_new_tokens=60, do_sample=False)[0]['generated_text']
    response = out.split("<|im_start|>assistant\n")[-1].replace("<|im_end|>", "").strip()
    before_responses.append(response)
    print(f"\nQ: {q}\nA: {response}")

from peft import LoraConfig, get_peft_model

peft_config = LoraConfig(
    r=8,                       # Rank: Rank of low-rank matrix decomposition
    lora_alpha=16,             # Scaling factor for LoRA weights
    lora_dropout=0.05,         # Dropout probability to prevent overfitting
    target_modules=["q_proj", "v_proj"], # Apply to Query and Value attention projections
    bias="none",
    task_type="CAUSAL_LM"
)

from trl import SFTTrainer, SFTConfig

training_args = SFTConfig(
    output_dir="./results",
    num_train_epochs=5,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    dataset_text_field="text",
    max_length=256, # Changed from max_seq_length
    logging_steps=5,
    save_strategy="no",
    fp16=True
)

trainer = SFTTrainer(
    model=model,
    train_dataset=formatted_dataset,
    peft_config=peft_config,
    args=training_args
)

trainer.train()

adapter_path = "./fastapi_lora_adapter"
trainer.model.save_pretrained(adapter_path)
tokenizer.save_pretrained(adapter_path)

print(f"Adapter successfully saved to {adapter_path}")

print("=== AFTER FINE-TUNING RESPONSES ===")
after_responses = []

# Generate using modified adapter weights
for q in test_questions:
    prompt = f"<|im_start|>user\n{q}<|im_end|>\n<|im_start|>assistant\n"
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    outputs = model.generate(**inputs, max_new_tokens=60, do_sample=False)
    out_text = tokenizer.decode(outputs[0], skip_special_tokens=False)
    response = out_text.split("<|im_start|>assistant\n")[-1].replace("<|im_end|>", "").strip()
    after_responses.append(response)

# Output evaluation comparison
import pandas as pd
df_comp = pd.DataFrame({
    "Question": test_questions,
    "Before Fine-Tuning": before_responses,
    "After Fine-Tuning": after_responses
})
from IPython.display import display
display(df_comp)

